### ISSUE TITLE
NPE on ./gradlew runClient

### ISSUE THREAD

**Issue by jvpichowski** [DomenicDev/Crucified#17]
After launching the client only the the start screen is shown and then the client crashes.

```

$ ./gradlew runClient
:compileJava UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:assets:compileJava NO-SOURCE
:assets:processResources UP-TO-DATE
:assets:classes UP-TO-DATE
:assets:jar UP-TO-DATE
:runClientAug 06, 2017 4:57:12 PM com.jme3.system.JmeDesktopSystem initialize
INFORMATION: Running on jMonkeyEngine 3.1-stable
 * Branch: HEAD
 * Git Hash: af04bf9
 * Build Date: 2017-02-13
Aug 06, 2017 4:57:13 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFORMATION: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: igdumdim64
 * Driver Version: 10.18.10.4425
 * Scaling Factor: 1
Aug 06, 2017 4:57:14 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFORMATION: OpenGL Renderer Information
 * Vendor: Intel
 * Renderer: Intel(R) HD Graphics 4000
 * OpenGL Version: 4.0.0 - Build 10.18.10.4425
 * GLSL Version: 4.00 - Build 10.18.10.4425
 * Profile: Compatibility
Aug 06, 2017 4:57:14 PM com.jme3.renderer.opengl.GLRenderer setMainFrameBufferSrgb
WARNUNG: Driver claims that default framebuffer is not sRGB capable. Enabling anyway.
Aug 06, 2017 4:57:14 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMATION: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
Aug 06, 2017 4:57:14 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNUNG: Pausing audio device not supported.
Aug 06, 2017 4:57:14 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMATION: Audio effect extension version: 1.0
Aug 06, 2017 4:57:14 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMATION: Audio max auxiliary sends: 4
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:244)
        at com.jme3.network.kernel.tcp.SocketConnector.<init>(SocketConnector.java:65)
        at com.jme3.network.Network.connectToServer(Network.java:165)
        at com.jme3.network.Network.connectToServer(Network.java:122)
        at de.gamedevbaden.crucified.net.client.GameClient.connect(GameClient.java:42)
        at de.gamedevbaden.crucified.tests.SimpleClientServerTest.ClientTest.simpleInitApp(ClientTest.java:34)
        at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
        at java.lang.Thread.run(Thread.java:745)

Bullet-Native: Initializing java classes
Aug 06, 2017 4:57:15 PM com.jme3.app.LegacyApplication handleError
SCHWERWIEGEND: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.NullPointerException
        at de.gamedevbaden.crucified.utils.GameInitializer.initClientStatesWithGameSessionDependency(GameInitializer.java:72)
        at de.gamedevbaden.crucified.tests.SimpleClientServerTest.ClientTest.simpleInitApp(ClientTest.java:53)
        at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
        at java.lang.Thread.run(Thread.java:745)


BUILD SUCCESSFUL

Total time: 28.188 secs

```

**Comment by DomenicDev** [comment]
This happens when no server has been started. "TestClient" is just for testing and requires a running server.
To not start a server every time you can use "SingleplayerTest" instead.
